### ISSUE TITLE
F# samples/posts

### ISSUE THREAD

**Issue by bartelink** [edgarjrg/eventstore-resource-collection#1]
Nice work!

Just said I'd drop a note in case you happen not to be aware of these:

Andrew C Meier's tutorial has some good coverage and a pretty impressive overall app/example, linked from https://github.com/jet/equinox#ameier38s-tutorial

Also, https://github.com/jet/dotnet-templates has some slightly extended equinox examples (they're not worthy of a separate listing as they are pretty much all derived from https://github.com/jet/equinox/samples which you already have); more will be added over time, but the timing depends on the ever shifting sands of prioritisation (docs for propulsion are higher priority than more samples in this general space)

**Comment by codingedgar** [comment]
Thanks for taking the interest @bartelink 💛 

> Andrew C Meier's tutorial has some good coverage and a pretty impressive overall app/example, linked from https://github.com/jet/equinox#ameier38s-tutorial

WOW that's such a good example 😻

>(docs for propulsion are higher priority than more samples in this general space)

Propulsion looks so amazing, also agree that docs are higher priority, I still feel short to understand it.

You guys at @jet seem to be using EventStore a lot! I also want to list companies using the tool to try to understand/show the employability for people learning/knowing EventStore and list use cases of how they're using the tool.

Thanks you so much for contributing 🙏

**Comment by bartelink** [comment]
Take a bow @ameier38 ;)

Propulsion was definitely interesting to write (it evolved from optimising a large data sync job but has turned out to have broader applicability)

A final recommendation is https://github.com/ddd-cqrs-es/slack-community - there's lots of folks on the same journey

Not sure whether getting a real list of EventStore and/or event sourcing usage together is that viable a task; there's just so many companies out there that don't divulge such info.

**Comment by codingedgar** [comment]
> Not sure whether getting a real list of EventStore and/or event sourcing usage together is that viable a task

I've seen so much info of Event Sourcing that is easy to google basic stuff and find lots of books, but EventStore info is so scarce, not sure if it adds making yet-another-ddd-cqrs-es-list 📚 , but if any DDD/CQRS/ES example is using EventStore directly is worth mentioning it 🎯

> there's just so many companies out there that don't divulge such info

Oh sure! But some do, hope to find those 🕵
